FROM alpine:3.12.3

LABEL MAINTAINER='Prakash Khadka'

RUN mkdir -p /var/www/html 
WORKDIR /var/www/html

RUN apk update && \
    apk add nginx 

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY public_html/ .

RUN  mkdir -p /run/nginx/ && \
     touch /run/nginx/nginx.pid && \
     chown nginx:nginx /run/nginx -R

VOLUME /var/www/html/wp-content/uploads

EXPOSE 8080

RUN rm -rf /var/cache/apk/*

CMD ["nginx", "-g", "daemon off;"]
